language: node_js
node_js: node
os: osx
script: npm run dist
deploy:
  provider: releases
  api_key:
    secure: vv8g5479fmPlwbafE1CYxZwiK6+LYLUr0Oo0oz+hoTQeOKYTJFE15hmQLC2vUBcKaBB7yqoP9dPZyXQouhMws3mwGz2RmaprgCj1qbZei/l2RxIqQZVZjJJ1MicYF12LzT5DBJV93jXUsEimn584JLgrzDd1hV9IcUp3T6Six9FOou3lIxV+63Un/rMhPa13xku1EB5zixzCp4K7M575A41k2OBD5brZA3F/cKd37sjfUOU6KcJHhbzPSa+mild7lypT/rlcHwOfIp9lI3wXgLNLODJBfxmZQHloCsrCBYPT+28KWg/L5zMEWNOt4zFUYwicgI7yRw+Bm7Koj8WkYelAMHwr0GmCdSZLaJyg6EbA6o1B1D+dKImbL1iaJbGSg8BDseuOgOvx402DtkFGSUjWTD1eYepa+p3jj9xPaRY5eiYttN7gB42Qc0xz+xwMA/PGFKnKlwarviShp0R2B05T01uxun4ZudHH9bmPVwKPK6HYW4kSxHsidhkQucy/imHMefic8E1+IAO3gNXWJkVfNFzksqUf1ir6Ziz0zjAUr2rLCJkM3z9h0/55uyGI7TQ9vtqwgio8JYxqr4Vp2zvw3zEzI1GL4dC2gctB6+nYW0JVfTYiwrcJB/MfJMHPJnhxMbLyo9Jfk1PiwXcHT5363FdPhQNbNVLyM5ejbmk=
  file_glob: true
  file: dist/mac/*.dmg
  skip_cleanup: true
  on:
    tags: true
notifications:
  email:
    on_success: always
    on_failure: always